<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            ['name_ar' => 'أفغاني', 'name_en' => 'Afghan'],
            ['name_ar' => 'ألباني', 'name_en' => 'Albanian'],
            ['name_ar' => 'جزائري', 'name_en' => 'Algerian'],
            ['name_ar' => 'أمريكي', 'name_en' => 'American'],
            ['name_ar' => 'أندوري', 'name_en' => 'Andorran'],
            ['name_ar' => 'أنغولي', 'name_en' => 'Angolan'],
            ['name_ar' => 'أنتيغوي وبربودي', 'name_en' => 'Antiguan and Barbudan'],
            ['name_ar' => 'أرجنتيني', 'name_en' => 'Argentine'],
            ['name_ar' => 'أرميني', 'name_en' => 'Armenian'],
            ['name_ar' => 'أسترالي', 'name_en' => 'Australian'],
            ['name_ar' => 'نمساوي', 'name_en' => 'Austrian'],
            ['name_ar' => 'أذربيجاني', 'name_en' => 'Azerbaijani'],
            ['name_ar' => 'بهامي', 'name_en' => 'Bahamian'],
            ['name_ar' => 'بحريني', 'name_en' => 'Bahraini'],
            ['name_ar' => 'بنغلاديشي', 'name_en' => 'Bangladeshi'],
            ['name_ar' => 'باربادوسي', 'name_en' => 'Barbadian'],
            ['name_ar' => 'بيلاروسي', 'name_en' => 'Belarusian'],
            ['name_ar' => 'بلجيكي', 'name_en' => 'Belgian'],
            ['name_ar' => 'بليزي', 'name_en' => 'Belizean'],
            ['name_ar' => 'بنيني', 'name_en' => 'Beninese'],
            ['name_ar' => 'بوتاني', 'name_en' => 'Bhutanese'],
            ['name_ar' => 'بوليفي', 'name_en' => 'Bolivian'],
            ['name_ar' => 'بوسني', 'name_en' => 'Bosnian'],
            ['name_ar' => 'بوتسواني', 'name_en' => 'Botswanan'],
            ['name_ar' => 'برازيلي', 'name_en' => 'Brazilian'],
            ['name_ar' => 'بريطاني', 'name_en' => 'British'],
            ['name_ar' => 'بروناي', 'name_en' => 'Bruneian'],
            ['name_ar' => 'بلغاري', 'name_en' => 'Bulgarian'],
            ['name_ar' => 'بوركينابي', 'name_en' => 'Burkinabe'],
            ['name_ar' => 'بوروندي', 'name_en' => 'Burundian'],
            ['name_ar' => 'كمبودي', 'name_en' => 'Cambodian'],
            ['name_ar' => 'كاميروني', 'name_en' => 'Cameroonian'],
            ['name_ar' => 'كندي', 'name_en' => 'Canadian'],
            ['name_ar' => 'كيب فيردي', 'name_en' => 'Cape Verdean'],
            ['name_ar' => 'تشادي', 'name_en' => 'Chadian'],
            ['name_ar' => 'شيلي', 'name_en' => 'Chilean'],
            ['name_ar' => 'صيني', 'name_en' => 'Chinese'],
            ['name_ar' => 'كولومبي', 'name_en' => 'Colombian'],
            ['name_ar' => 'كوموري', 'name_en' => 'Comorian'],
            ['name_ar' => 'كونغولي', 'name_en' => 'Congolese (Congo-Brazzaville)'],
            ['name_ar' => 'كونغولي', 'name_en' => 'Congolese (Congo-Kinshasa)'],
            ['name_ar' => 'كوستاريكي', 'name_en' => 'Costa Rican'],
            ['name_ar' => 'كرواتي', 'name_en' => 'Croatian'],
            ['name_ar' => 'كوبي', 'name_en' => 'Cuban'],
            ['name_ar' => 'قبرصي', 'name_en' => 'Cypriot'],
            ['name_ar' => 'تشيكي', 'name_en' => 'Czech'],
            ['name_ar' => 'دنماركي', 'name_en' => 'Danish'],
            ['name_ar' => 'جيبوتي', 'name_en' => 'Djiboutian'],
            ['name_ar' => 'دومينيكي', 'name_en' => 'Dominican'],
            ['name_ar' => 'هولندي', 'name_en' => 'Dutch'],
            ['name_ar' => 'إكوادوري', 'name_en' => 'Ecuadorian'],
            ['name_ar' => 'مصري', 'name_en' => 'Egyptian'],
            ['name_ar' => 'إماراتي', 'name_en' => 'Emirati'],
            ['name_ar' => 'غيني', 'name_en' => 'Equatorial Guinean'],
            ['name_ar' => 'إريتري', 'name_en' => 'Eritrean'],
            ['name_ar' => 'إستوني', 'name_en' => 'Estonian'],
            ['name_ar' => 'إثيوبي', 'name_en' => 'Ethiopian'],
            ['name_ar' => 'فيجي', 'name_en' => 'Fijian'],
            ['name_ar' => 'فنلندي', 'name_en' => 'Finnish'],
            ['name_ar' => 'فرنسي', 'name_en' => 'French'],
            ['name_ar' => 'غابوني', 'name_en' => 'Gabonese'],
            ['name_ar' => 'غامبي', 'name_en' => 'Gambian'],
            ['name_ar' => 'جورجي', 'name_en' => 'Georgian'],
            ['name_ar' => 'ألماني', 'name_en' => 'German'],
            ['name_ar' => 'غاني', 'name_en' => 'Ghanaian'],
            ['name_ar' => 'يوناني', 'name_en' => 'Greek'],
            ['name_ar' => 'غواتيمالي', 'name_en' => 'Guatemalan'],
            ['name_ar' => 'غيني', 'name_en' => 'Guinean'],
            ['name_ar' => 'غيني بيساوي', 'name_en' => 'Guinea-Bissauan'],
            ['name_ar' => 'غوياني', 'name_en' => 'Guyanese'],
            ['name_ar' => 'هايتي', 'name_en' => 'Haitian'],
            ['name_ar' => 'هندوراسي', 'name_en' => 'Honduran'],
            ['name_ar' => 'هنغاري', 'name_en' => 'Hungarian'],
            ['name_ar' => 'آيسلندي', 'name_en' => 'Icelandic'],
            ['name_ar' => 'هندي', 'name_en' => 'Indian'],
            ['name_ar' => 'إندونيسي', 'name_en' => 'Indonesian'],
            ['name_ar' => 'إيراني', 'name_en' => 'Iranian'],
            ['name_ar' => 'عراقي', 'name_en' => 'Iraqi'],
            ['name_ar' => 'إيرلندي', 'name_en' => 'Irish'],
            ['name_ar' => 'إسرائيلي', 'name_en' => 'Israeli'],
            ['name_ar' => 'إيطالي', 'name_en' => 'Italian'],
            ['name_ar' => 'جامايكي', 'name_en' => 'Jamaican'],
            ['name_ar' => 'ياباني', 'name_en' => 'Japanese'],
            ['name_ar' => 'أردني', 'name_en' => 'Jordanian'],
            ['name_ar' => 'كازاخستاني', 'name_en' => 'Kazakhstani'],
            ['name_ar' => 'كيني', 'name_en' => 'Kenyan'],
            ['name_ar' => 'كويتي', 'name_en' => 'Kuwaiti'],
            ['name_ar' => 'قرغيزي', 'name_en' => 'Kyrgyzstani'],
            ['name_ar' => 'لاوسي', 'name_en' => 'Laotian'],
            ['name_ar' => 'لاتيفي', 'name_en' => 'Latvian'],
            ['name_ar' => 'لبناني', 'name_en' => 'Lebanese'],
            ['name_ar' => 'ليبيري', 'name_en' => 'Liberian'],
            ['name_ar' => 'ليبي', 'name_en' => 'Libyan'],
            ['name_ar' => 'ليتواني', 'name_en' => 'Lithuanian'],
            ['name_ar' => 'مقدوني', 'name_en' => 'Macedonian'],
            ['name_ar' => 'مالاغاشي', 'name_en' => 'Malagasy'],
            ['name_ar' => 'مالاوي', 'name_en' => 'Malawian'],
            ['name_ar' => 'ماليزي', 'name_en' => 'Malaysian'],
            ['name_ar' => 'مالديفي', 'name_en' => 'Maldivian'],
            ['name_ar' => 'مالي', 'name_en' => 'Malian'],
            ['name_ar' => 'مالطي', 'name_en' => 'Maltese'],
            ['name_ar' => 'ماوريتي', 'name_en' => 'Mauritian'],
            ['name_ar' => 'مغربي', 'name_en' => 'Moroccan'],
            ['name_ar' => 'موزمبيقي', 'name_en' => 'Mozambican'],
            ['name_ar' => 'ناميبي', 'name_en' => 'Namibian'],
            ['name_ar' => 'نيبالي', 'name_en' => 'Nepalese'],
            ['name_ar' => 'نيوزيلندي', 'name_en' => 'New Zealander'],
            ['name_ar' => 'نيجيري', 'name_en' => 'Nigerian'],
            ['name_ar' => 'عماني', 'name_en' => 'Omani'],
            ['name_ar' => 'باكستاني', 'name_en' => 'Pakistani'],
            ['name_ar' => 'فلسطيني', 'name_en' => 'Palestinian'],
            ['name_ar' => 'قطري', 'name_en' => 'Qatari'],
            ['name_ar' => 'روسي', 'name_en' => 'Russian'],
            ['name_ar' => 'رواندي', 'name_en' => 'Rwandan'],
            ['name_ar' => 'صومالي', 'name_en' => 'Somali'],
            ['name_ar' => 'سوري', 'name_en' => 'Syrian'],
            ['name_ar' => 'تونسي', 'name_en' => 'Tunisian'],
            ['name_ar' => 'تركي', 'name_en' => 'Turkish'],
            ['name_ar' => 'إماراتي', 'name_en' => 'Emirati'],
            ['name_ar' => 'يمني', 'name_en' => 'Yemeni'],
        ];
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Nationality::truncate();

        DB::table('nationalities')->insert($nationalities);
    }
}
